#!/data/work/project/mosclient_venv/bin/python
#!/usr/bin/env python2
import sys
import re
import os
from keepasshttp import KeePassHTTP
from requests.exceptions import ConnectionError
keyfile_path = os.path.join(os.path.expanduser('~'), '.kphttpclikey.yml')

repo_info_regex = r'(\S+)=(.*)'

operation = sys.argv[1]
if operation != "get":
    sys.exit(1)


repo_info_string = sys.stdin.read()
repo_info = dict(re.findall(repo_info_regex, repo_info_string))

if 'host' not in repo_info:
    sys.stderr.write("Host not set\n")
    sys.exit(1)

if operation == "get":

    if not os.path.exists(keyfile_path):
        client = keepasshttp.KeePassHTTP(port=19455)
        client.associate()
        client.write_to_filepath(keyfile_path)
    else:
        client = KeePassHTTP.from_filepath(keyfile_path)

    repo_logins = client.get_logins('%s://%s/' % (repo_info['protocol'], repo_info['host']))
    if repo_logins:
        print("username=%s" % repo_logins[0]['login'])
        print("password=%s" % repo_logins[0]['password'])
    else:
        sys.stderr.write("Couldn't find credentials for host\n")
        sys.exit(1)
